#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfda3;
constexpr uint24_t FX_DATA_BYTES = 150558;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Constants
{
}

namespace Levels
{
  constexpr uint24_t Level_00 = 0x000000;
  constexpr uint24_t Level_00_Details = 0x0000B0;
  constexpr uint24_t Level_01 = 0x0000B3;
  constexpr uint24_t Level_01_Details = 0x000163;
  constexpr uint24_t Level_02 = 0x000166;
  constexpr uint24_t Level_02_Details = 0x000216;
  constexpr uint24_t Level_03 = 0x000219;
  constexpr uint24_t Level_03_Details = 0x0002C9;
  constexpr uint24_t Level_04 = 0x0002CC;
  constexpr uint24_t Level_04_Details = 0x00037C;
  constexpr uint24_t Level_05 = 0x00037F;
  constexpr uint24_t Level_05_Details = 0x00042F;
  constexpr uint24_t Level_06 = 0x000432;
  constexpr uint24_t Level_06_Details = 0x0004E2;
  constexpr uint24_t Level_07 = 0x0004E5;
  constexpr uint24_t Level_07_Details = 0x000595;
  constexpr uint24_t Level_08 = 0x000598;
  constexpr uint24_t Level_08_Details = 0x000648;
  constexpr uint24_t Level_09 = 0x00064B;
  constexpr uint24_t Level_09_Details = 0x0006FB;
  constexpr uint24_t Level_10 = 0x0006FE;
  constexpr uint24_t Level_10_Details = 0x0007AE;
  constexpr uint24_t Level_11 = 0x0007B1;
  constexpr uint24_t Level_11_Details = 0x000861;
  constexpr uint24_t Level_12 = 0x000864;
  constexpr uint24_t Level_12_Details = 0x000914;
  constexpr uint24_t Level_13 = 0x000917;
  constexpr uint24_t Level_13_Details = 0x0009C7;
  constexpr uint24_t Level_14 = 0x0009CA;
  constexpr uint24_t Level_14_Details = 0x000A7A;
  constexpr uint24_t Level_15 = 0x000A7D;
  constexpr uint24_t Level_15_Details = 0x000B2D;
  constexpr uint24_t Level_16 = 0x000B30;
  constexpr uint24_t Level_16_Details = 0x000BE0;
  constexpr uint24_t Level_17 = 0x000BE3;
  constexpr uint24_t Level_17_Details = 0x000C93;
  constexpr uint24_t Level_18 = 0x000C96;
  constexpr uint24_t Level_18_Details = 0x000D46;
  constexpr uint24_t Level_19 = 0x000D49;
  constexpr uint24_t Level_19_Details = 0x000DF9;
  constexpr uint24_t Level_20 = 0x000DFC;
  constexpr uint24_t Level_20_Details = 0x000EAC;
  constexpr uint24_t Level_21 = 0x000EAF;
  constexpr uint24_t Level_21_Details = 0x000F5F;
  constexpr uint24_t Level_22 = 0x000F62;
  constexpr uint24_t Level_22_Details = 0x001012;
  constexpr uint24_t Level_23 = 0x001015;
  constexpr uint24_t Level_23_Details = 0x0010C5;
  constexpr uint24_t Levels = 0x0010C8;
  constexpr uint24_t Level_Details = 0x001110;
}

namespace Images
{
  constexpr uint24_t PPOT = 0x001158;
  constexpr uint24_t Scoundrel = 0x00415A;
  constexpr uint24_t Tiles = 0x004D5C;
  constexpr uint24_t ClearProgress = 0x00535E;
  constexpr uint24_t Menu = 0x0054AA;
  constexpr uint24_t Title_Top = 0x0072AC;
  constexpr uint24_t Title_Bottom = 0x0084AE;
  constexpr uint24_t Title_Lava = 0x0099B0;
  constexpr uint24_t Title_Amp = 0x009F1C;
  constexpr uint24_t Title_Aqua = 0x00A086;
  constexpr uint24_t Levels_Select = 0x00A5E0;
  constexpr uint24_t Levels_Cursor = 0x00BC32;
  constexpr uint24_t Levels_HUD = 0x00BDCC;
  constexpr uint24_t Levels_Status = 0x00DB9E;
  constexpr uint24_t Levels_Number = 0x00DD23;
  constexpr uint24_t Levels_NumberOfMoves = 0x00E24D;
  constexpr uint24_t Levels_NumberOfMoves_Numbers = 0x00E363;
  constexpr uint24_t Mini_HUD = 0x00E3FB;
  constexpr uint24_t Numbers_HUD = 0x00E4BD;
  constexpr uint24_t Lava_01 = 0x00EE1F;
  constexpr uint24_t Lava_02 = 0x00EE81;
  constexpr uint24_t Lava_03 = 0x00EF43;
  constexpr uint24_t Lava_04 = 0x00F065;
  constexpr uint24_t Lava_05 = 0x00F1E7;
  constexpr uint24_t Lava_06 = 0x00F3C9;
  constexpr uint24_t Lava_07 = 0x00F60B;
  constexpr uint24_t Lava_08 = 0x00F8AD;
  constexpr uint24_t Water_01 = 0x00FBAF;
  constexpr uint24_t Water_02 = 0x00FC11;
  constexpr uint24_t Water_03 = 0x00FCD3;
  constexpr uint24_t Water_04 = 0x00FDF5;
  constexpr uint24_t Water_05 = 0x00FF77;
  constexpr uint24_t Water_06 = 0x010159;
  constexpr uint24_t Water_07 = 0x01039B;
  constexpr uint24_t Water_08 = 0x01063D;
  constexpr uint24_t Numbers_5x3_2D_WB = 0x01093F;
  constexpr uint24_t Level_Img_00 = 0x0112A1;
  constexpr uint24_t Level_Img_01 = 0x011C12;
  constexpr uint24_t Level_Img_02 = 0x01298E;
  constexpr uint24_t Level_Img_03 = 0x01370A;
  constexpr uint24_t Level_Img_04 = 0x014486;
  constexpr uint24_t Level_Img_05 = 0x015202;
  constexpr uint24_t Level_Img_06 = 0x015F7E;
  constexpr uint24_t Level_Img_07 = 0x016CFA;
  constexpr uint24_t Level_Img_08 = 0x017A76;
  constexpr uint24_t Level_Img_09 = 0x0187F2;
  constexpr uint24_t Level_Img_10 = 0x01956E;
  constexpr uint24_t Level_Img_11 = 0x01A2EA;
  constexpr uint24_t Level_Img_12 = 0x01B066;
  constexpr uint24_t Level_Img_13 = 0x01BDE2;
  constexpr uint24_t Level_Img_14 = 0x01CB5E;
  constexpr uint24_t Level_Img_15 = 0x01D8DA;
  constexpr uint24_t Level_Img_16 = 0x01E566;
  constexpr uint24_t Level_Img_17 = 0x01F2E2;
  constexpr uint24_t Level_Img_18 = 0x01FD8E;
  constexpr uint24_t Level_Img_19 = 0x020A1A;
  constexpr uint24_t Level_Img_20 = 0x021796;
  constexpr uint24_t Level_Img_21 = 0x022512;
  constexpr uint24_t Level_Img_22 = 0x0230AE;
  constexpr uint24_t Level_Img_23 = 0x023E2A;
  constexpr uint24_t Level_Images = 0x024BA6;
  constexpr uint24_t Lavas = 0x024BEE;
  constexpr uint24_t Waters = 0x024C06;
}

