#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfdac;
constexpr uint24_t FX_DATA_BYTES = 148463;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Constants
{
}

namespace Levels
{
  constexpr uint24_t Level_00 = 0x000000;
  constexpr uint24_t Level_00_Details = 0x0000B0;
  constexpr uint24_t Level_01 = 0x0000B3;
  constexpr uint24_t Level_01_Details = 0x000163;
  constexpr uint24_t Level_02 = 0x000166;
  constexpr uint24_t Level_02_Details = 0x000216;
  constexpr uint24_t Level_03 = 0x000219;
  constexpr uint24_t Level_03_Details = 0x0002C9;
  constexpr uint24_t Level_04 = 0x0002CC;
  constexpr uint24_t Level_04_Details = 0x00037C;
  constexpr uint24_t Level_05 = 0x00037F;
  constexpr uint24_t Level_05_Details = 0x00042F;
  constexpr uint24_t Level_06 = 0x000432;
  constexpr uint24_t Level_06_Details = 0x0004E2;
  constexpr uint24_t Level_07 = 0x0004E5;
  constexpr uint24_t Level_07_Details = 0x000595;
  constexpr uint24_t Level_08 = 0x000598;
  constexpr uint24_t Level_08_Details = 0x000648;
  constexpr uint24_t Level_09 = 0x00064B;
  constexpr uint24_t Level_09_Details = 0x0006FB;
  constexpr uint24_t Level_10 = 0x0006FE;
  constexpr uint24_t Level_10_Details = 0x0007AE;
  constexpr uint24_t Level_11 = 0x0007B1;
  constexpr uint24_t Level_11_Details = 0x000861;
  constexpr uint24_t Level_12 = 0x000864;
  constexpr uint24_t Level_12_Details = 0x000914;
  constexpr uint24_t Level_13 = 0x000917;
  constexpr uint24_t Level_13_Details = 0x0009C7;
  constexpr uint24_t Level_14 = 0x0009CA;
  constexpr uint24_t Level_14_Details = 0x000A7A;
  constexpr uint24_t Level_15 = 0x000A7D;
  constexpr uint24_t Level_15_Details = 0x000B2D;
  constexpr uint24_t Level_16 = 0x000B30;
  constexpr uint24_t Level_16_Details = 0x000BE0;
  constexpr uint24_t Level_17 = 0x000BE3;
  constexpr uint24_t Level_17_Details = 0x000C93;
  constexpr uint24_t Level_18 = 0x000C96;
  constexpr uint24_t Level_18_Details = 0x000D46;
  constexpr uint24_t Level_19 = 0x000D49;
  constexpr uint24_t Level_19_Details = 0x000DF9;
  constexpr uint24_t Level_20 = 0x000DFC;
  constexpr uint24_t Level_20_Details = 0x000EAC;
  constexpr uint24_t Level_21 = 0x000EAF;
  constexpr uint24_t Level_21_Details = 0x000F5F;
  constexpr uint24_t Level_22 = 0x000F62;
  constexpr uint24_t Level_22_Details = 0x001012;
  constexpr uint24_t Level_23 = 0x001015;
  constexpr uint24_t Level_23_Details = 0x0010C5;
  constexpr uint24_t Levels = 0x0010C8;
  constexpr uint24_t Level_Details = 0x001110;
}

namespace Images
{
  constexpr uint24_t PPOT = 0x001158;
  constexpr uint24_t Scoundrel = 0x00415A;
  constexpr uint24_t Tiles = 0x004D5C;
  constexpr uint24_t ClearProgress = 0x00535E;
  constexpr uint24_t Levels_Select = 0x0054AA;
  constexpr uint24_t Levels_Cursor = 0x006AFC;
  constexpr uint24_t Levels_HUD = 0x006C96;
  constexpr uint24_t Levels_Status = 0x008A68;
  constexpr uint24_t Levels_Number = 0x008BED;
  constexpr uint24_t Levels_NumberOfMoves = 0x009117;
  constexpr uint24_t Levels_NumberOfMoves_Numbers = 0x00922D;
  constexpr uint24_t Lava_01 = 0x0092C5;
  constexpr uint24_t Lava_02 = 0x009327;
  constexpr uint24_t Lava_03 = 0x0093E9;
  constexpr uint24_t Lava_04 = 0x00950B;
  constexpr uint24_t Lava_05 = 0x00968D;
  constexpr uint24_t Lava_06 = 0x00986F;
  constexpr uint24_t Lava_07 = 0x009AB1;
  constexpr uint24_t Lava_08 = 0x009D53;
  constexpr uint24_t Water_01 = 0x00A055;
  constexpr uint24_t Water_02 = 0x00A0B7;
  constexpr uint24_t Water_03 = 0x00A179;
  constexpr uint24_t Water_04 = 0x00A29B;
  constexpr uint24_t Water_05 = 0x00A41D;
  constexpr uint24_t Water_06 = 0x00A5FF;
  constexpr uint24_t Water_07 = 0x00A841;
  constexpr uint24_t Water_08 = 0x00AAE3;
  constexpr uint24_t Numbers_5x3_2D_WB = 0x00ADE5;
  constexpr uint24_t Level_Img_00 = 0x00B747;
  constexpr uint24_t Level_Img_01 = 0x00C7C9;
  constexpr uint24_t Level_Img_02 = 0x00D84B;
  constexpr uint24_t Level_Img_03 = 0x00E8CD;
  constexpr uint24_t Level_Img_04 = 0x00F94F;
  constexpr uint24_t Level_Img_05 = 0x0109D1;
  constexpr uint24_t Level_Img_06 = 0x011A53;
  constexpr uint24_t Level_Img_07 = 0x012AD5;
  constexpr uint24_t Level_Img_08 = 0x013B57;
  constexpr uint24_t Level_Img_09 = 0x014BD9;
  constexpr uint24_t Level_Img_10 = 0x015C5B;
  constexpr uint24_t Level_Img_11 = 0x016CDD;
  constexpr uint24_t Level_Img_12 = 0x017D5F;
  constexpr uint24_t Level_Img_13 = 0x018DE1;
  constexpr uint24_t Level_Img_14 = 0x019E63;
  constexpr uint24_t Level_Img_15 = 0x01AEE5;
  constexpr uint24_t Level_Img_16 = 0x01BF67;
  constexpr uint24_t Level_Img_17 = 0x01CFE9;
  constexpr uint24_t Level_Img_18 = 0x01E06B;
  constexpr uint24_t Level_Img_19 = 0x01F0ED;
  constexpr uint24_t Level_Img_20 = 0x02016F;
  constexpr uint24_t Level_Img_21 = 0x0211F1;
  constexpr uint24_t Level_Img_22 = 0x022273;
  constexpr uint24_t Level_Img_23 = 0x0232F5;
  constexpr uint24_t Level_Images = 0x024377;
  constexpr uint24_t Lavas = 0x0243BF;
  constexpr uint24_t Waters = 0x0243D7;
}

