#pragma once

/**** FX data header generated by fxdata-build.py tool version 1.13 ****/

using uint24_t = __uint24;

// Initialize FX hardware using  FX::begin(FX_DATA_PAGE); in the setup() function.

constexpr uint16_t FX_DATA_PAGE  = 0xfd6a;
constexpr uint24_t FX_DATA_BYTES = 165175;

constexpr uint16_t FX_SAVE_PAGE  = 0xfff0;
constexpr uint24_t FX_SAVE_BYTES = 2;

namespace Constants
{
}

namespace Levels
{
  constexpr uint24_t Level_00 = 0x000000;
  constexpr uint24_t Level_01 = 0x00007E;
  constexpr uint24_t Level_02 = 0x0000FC;
  constexpr uint24_t Level_03 = 0x00017A;
  constexpr uint24_t Level_04 = 0x0001F8;
  constexpr uint24_t Level_05 = 0x000276;
  constexpr uint24_t Level_06 = 0x0002F4;
  constexpr uint24_t Level_07 = 0x000372;
  constexpr uint24_t Level_08 = 0x0003F0;
  constexpr uint24_t Level_09 = 0x00046E;
  constexpr uint24_t Level_10 = 0x0004EC;
  constexpr uint24_t Level_11 = 0x00056A;
  constexpr uint24_t Level_12 = 0x0005E8;
  constexpr uint24_t Level_13 = 0x000666;
  constexpr uint24_t Level_14 = 0x0006E4;
  constexpr uint24_t Level_15 = 0x000762;
  constexpr uint24_t Level_16 = 0x0007E0;
  constexpr uint24_t Level_17 = 0x00085E;
  constexpr uint24_t Level_18 = 0x0008DC;
  constexpr uint24_t Level_19 = 0x00095A;
  constexpr uint24_t Level_20 = 0x0009D8;
  constexpr uint24_t Level_21 = 0x000A56;
  constexpr uint24_t Level_22 = 0x000AD4;
  constexpr uint24_t Level_23 = 0x000B52;
  constexpr uint24_t Levels = 0x000BD0;
}

namespace Images
{
  constexpr uint24_t PPOT = 0x000C18;
  constexpr uint24_t ClearProgress = 0x003C1A;
  constexpr uint24_t Menu = 0x003D66;
  constexpr uint24_t Title_Top = 0x005B68;
  constexpr uint24_t Title_Bottom = 0x006D6A;
  constexpr uint24_t Title_Lava = 0x00826C;
  constexpr uint24_t Title_Amp = 0x0087D8;
  constexpr uint24_t Title_Aqua = 0x008942;
  constexpr uint24_t Title_Good = 0x008E9C;
  constexpr uint24_t Title_Work = 0x0093F6;
  constexpr uint24_t Levels_Select = 0x009A70;
  constexpr uint24_t Levels_Cursor = 0x00B0C2;
  constexpr uint24_t Levels_HUD = 0x00B25C;
  constexpr uint24_t Levels_Status = 0x00D02E;
  constexpr uint24_t Levels_Number = 0x00D1B3;
  constexpr uint24_t Levels_NumberOfMoves = 0x00D6DD;
  constexpr uint24_t Levels_NumberOfMoves_Numbers = 0x00D7F3;
  constexpr uint24_t Puff = 0x00D88B;
  constexpr uint24_t Mini_HUD = 0x00F08D;
  constexpr uint24_t Numbers_HUD = 0x00F14F;
  constexpr uint24_t Tiles = 0x00FAB1;
  constexpr uint24_t Lava_01 = 0x0100B3;
  constexpr uint24_t Lava_02 = 0x010115;
  constexpr uint24_t Lava_03 = 0x0101D7;
  constexpr uint24_t Lava_04 = 0x0102F9;
  constexpr uint24_t Lava_05 = 0x01047B;
  constexpr uint24_t Lava_06 = 0x01065D;
  constexpr uint24_t Lava_07 = 0x01089F;
  constexpr uint24_t Lava_08 = 0x010B41;
  constexpr uint24_t Lava_09 = 0x010E43;
  constexpr uint24_t Lava_10 = 0x011145;
  constexpr uint24_t Lava_11 = 0x011447;
  constexpr uint24_t Lava_12 = 0x011749;
  constexpr uint24_t Lava_13 = 0x011A4B;
  constexpr uint24_t Lava_14 = 0x011D4D;
  constexpr uint24_t Water_01 = 0x01204F;
  constexpr uint24_t Water_02 = 0x0120B1;
  constexpr uint24_t Water_03 = 0x012173;
  constexpr uint24_t Water_04 = 0x012295;
  constexpr uint24_t Water_05 = 0x012417;
  constexpr uint24_t Water_06 = 0x0125F9;
  constexpr uint24_t Water_07 = 0x01283B;
  constexpr uint24_t Water_08 = 0x012ADD;
  constexpr uint24_t Water_09 = 0x012DDF;
  constexpr uint24_t Water_10 = 0x0130E1;
  constexpr uint24_t Water_11 = 0x0133E3;
  constexpr uint24_t Water_12 = 0x0136E5;
  constexpr uint24_t Water_13 = 0x0139E7;
  constexpr uint24_t Water_14 = 0x013CE9;
  constexpr uint24_t Numbers_5x3_2D_WB = 0x013FEB;
  constexpr uint24_t Level_Img_00 = 0x01494D;
  constexpr uint24_t Level_Img_01 = 0x015417;
  constexpr uint24_t Level_Img_02 = 0x016193;
  constexpr uint24_t Level_Img_03 = 0x016F0F;
  constexpr uint24_t Level_Img_04 = 0x017C8B;
  constexpr uint24_t Level_Img_05 = 0x018A07;
  constexpr uint24_t Level_Img_06 = 0x019783;
  constexpr uint24_t Level_Img_07 = 0x01A4FF;
  constexpr uint24_t Level_Img_08 = 0x01B27B;
  constexpr uint24_t Level_Img_09 = 0x01BFF7;
  constexpr uint24_t Level_Img_10 = 0x01CD73;
  constexpr uint24_t Level_Img_11 = 0x01DAEF;
  constexpr uint24_t Level_Img_12 = 0x01E86B;
  constexpr uint24_t Level_Img_13 = 0x01F5E7;
  constexpr uint24_t Level_Img_14 = 0x020363;
  constexpr uint24_t Level_Img_15 = 0x0210DF;
  constexpr uint24_t Level_Img_16 = 0x021D6B;
  constexpr uint24_t Level_Img_17 = 0x022AE7;
  constexpr uint24_t Level_Img_18 = 0x023593;
  constexpr uint24_t Level_Img_19 = 0x02421F;
  constexpr uint24_t Level_Img_20 = 0x024F9B;
  constexpr uint24_t Level_Img_21 = 0x025D17;
  constexpr uint24_t Level_Img_22 = 0x0269A3;
  constexpr uint24_t Level_Img_23 = 0x02771F;
  constexpr uint24_t Level_Images = 0x02849B;
  constexpr uint24_t Lavas = 0x0284E3;
  constexpr uint24_t Waters = 0x02850D;
}

